#LDFLAGS for loader flags; EXTRA_CFLAGS for file inclusion
#LDADD for linking and loading the library
SRCS=./src-test.c ./src.c 
PROG=verify_holes
CFLAGS=-g -Wall -I.
include /usr/lib/build/linux.prog.mk
